### ISSUE TITLE
ClassCastException in PDStream

### ISSUE THREAD

**Issue by gbm-bailleul** [gbm-bailleul/padaf#8]
For some PDF/A, getDictionaryObject does not return COSStream but other COSDictionary (super class)

```
public PDMetadata getMetadata()
{
    PDMetadata retval = null;
    COSStream mdStream = (COSStream)stream.getDictionaryObject( COSName.METADATA );
    if( mdStream != null )
    {
        retval = new PDMetadata( mdStream );
    }
    return retval;
}
```

org.apache.pdfbox.cos.COSDictionary cannot be cast to org.apache.pdfbox.cos.COSStream
        at org.apache.pdfbox.pdmodel.common.PDStream.getMetadata(PDStream.java:508)
        at net.padaf.preflight.font.AbstractFontValidator.checkFontFileMetaData(AbstractFontValidator.java:162)
        at net.padaf.preflight.font.Type1FontValidator.checkFontFileElement(Type1FontValidator.java:228)
        at net.padaf.preflight.font.Type1FontValidator.checkFontDescriptor(Type1FontValidator.java:125)
        at net.padaf.preflight.font.SimpleFontValidator.validate(SimpleFontValidator.java:264)
        at net.padaf.preflight.helpers.FontValidationHelper.validateFont(FontValidationHelper.java:107)
        at net.padaf.preflight.helpers.FontValidationHelper.innerValidate(FontValidationHelper.java:90)
        at net.padaf.preflight.helpers.AbstractValidationHelper.validate(AbstractValidationHelper.java:87)
        at net.padaf.preflight.AbstractValidator.runValidation(AbstractValidator.java:134)
        at net.padaf.preflight.PdfA1bValidator.validate(PdfA1bValidator.java:90)
        at net.padaf.preflight.Validator_A1b.main(Validator_A1b.java:47)

**Comment by gbm-bailleul** [comment]
Moved to PDFBox jira
